### ISSUE TITLE
Not find the develop-end.ova and the back-end.ova

### ISSUE THREAD

**Issue by milkcornjuice** [jarrocha/XinuBBB#1]
"Once you have installed VirtualBox, import Open Virtualization Format Virtual Machines from the same tarball that contains this file."
But in ./guide, there is no such file.

**Comment by jarrocha** [comment]
Hello, sorry for not getting back sooner. Are referring to the actual VirtualBox images? If so, try this link: https://drive.google.com/file/d/17JPbSik43i_cXrbGRivuhkmKw3d8NNzw/view?usp=sharing

**Comment by milkcornjuice** [comment]
Hello, I have found a place to download the mirror, thank you very much for your reply. 



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jarrocha/XinuBBB"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月7日(星期一) 上午9:14
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jarrocha/XinuBBB] Not find the develop-end.ova and the back-end.ova (#1)





 
Hello, sorry for not getting back sooner. Are referring to the actual VirtualBox images? If so, try this link: https://drive.google.com/file/d/17JPbSik43i_cXrbGRivuhkmKw3d8NNzw/view?usp=sharing
