### ISSUE TITLE
When booting from MicroSD Card

### ISSUE THREAD

**Issue by iheartcoffee** [jarrocha/XinuBBB#2]
I tried booting with the uEnv.txt settings as explained by you 
`bootfile=xinu.boot 
boot_mmc=fatload mmc 0 0x80200000 ${bootfile}; bootm 
uenvcmd=run boot_mmc
`

how ever the value needs to be slightly adjusted to
`
bootfile=xinu.boot 
boot_mmc=fatload mmc 0 0x82000000 ${bootfile}; bootm 
uenvcmd=run boot_mmc
`

The 80200000 needs to be changed to 82000000 on the README.md

**Comment by jarrocha** [comment]
That load value can actually change. If you see check other guides you will see different load addresses for different people. I suspect it got to do with the version of uboot in use.
